-- Tenant-safe channel adapter foundation, PR2 (channel-adapter-foundation
-- design, "Connection identity" decision): adds the generalized
-- ChannelConnection identity table plus nullable compatibility columns on
-- PhoneNumber/Conversation. Purely additive — no column drops, no renames,
-- no NOT NULL backfill required, so existing WhatsApp rows keep working
-- unmigrated (backfill lands in PR3).
--
-- Generated with `prisma migrate diff --from-url <fully-migrated scratch
-- db> --to-schema-datamodel prisma/schema.prisma --script` rather than
-- `prisma migrate dev`/`--from-migrations`: this repo's
-- 20260707190000_enable_rls_prisma_migrations migration makes the schema
-- engine's shadow-database replay fail with P3006/P1014
-- ("_prisma_migrations does not exist") every time it has to rebuild
-- history from scratch in a shadow DB — reproduced against a disposable
-- local Postgres, unrelated to this change. Diffing from an already fully
-- migrated live database sidesteps that shadow-DB replay entirely. Two
-- spurious `DROP INDEX` statements for the pg_trgm GIN indexes
-- (Conversation_customerName_trgm_idx / Conversation_customerPhone_trgm_idx,
-- added via raw CONCURRENTLY migrations not representable in
-- schema.prisma) were generated by that diff and are intentionally
-- excluded here — they are pre-existing, unrelated drift, not part of this
-- unit.

-- AlterTable
ALTER TABLE "PhoneNumber" ADD COLUMN     "channelConnectionId" TEXT;

-- AlterTable
ALTER TABLE "Conversation" ADD COLUMN     "channelConnectionId" TEXT,
ADD COLUMN     "externalParticipantId" TEXT;

-- CreateTable
CREATE TABLE "ChannelConnection" (
    "id" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "externalId" TEXT NOT NULL,
    "credentialId" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ChannelConnection_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ChannelConnection_businessId_idx" ON "ChannelConnection"("businessId");

-- CreateIndex
CREATE UNIQUE INDEX "ChannelConnection_provider_externalId_key" ON "ChannelConnection"("provider", "externalId");

-- AddForeignKey
ALTER TABLE "ChannelConnection" ADD CONSTRAINT "ChannelConnection_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Enable Row Level Security. Not generated by `prisma migrate dev` — hand
-- appended per project convention, see
-- 20260706000000_enable_rls_remaining_tables/migration.sql and
-- 20260707200000_add_webhook_event_outbox/migration.sql. Prisma connects as
-- table owner and bypasses RLS, so this is a no-op for the app; no policy
-- is created — nothing reads ChannelConnection through PostgREST or
-- Realtime.
ALTER TABLE "ChannelConnection" ENABLE ROW LEVEL SECURITY;
