-- CreateEnum
CREATE TYPE "WebhookEventStatus" AS ENUM ('pending', 'processing', 'done', 'failed');

-- CreateTable
CREATE TABLE "WebhookEvent" (
    "id" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "status" "WebhookEventStatus" NOT NULL DEFAULT 'pending',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 1,
    "nextRunAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "leaseExpiresAt" TIMESTAMP(3),
    "lockedBy" TEXT,
    "lastError" TEXT,
    "processedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WebhookEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "WebhookEvent_status_nextRunAt_idx" ON "WebhookEvent"("status", "nextRunAt");

-- CreateIndex
CREATE INDEX "WebhookEvent_status_leaseExpiresAt_idx" ON "WebhookEvent"("status", "leaseExpiresAt");

-- Enable Row Level Security. Not generated by `prisma migrate dev` — hand
-- appended per project convention, see
-- 20260706000000_enable_rls_remaining_tables/migration.sql:1-8. Prisma
-- connects as table owner and bypasses RLS, so this is a no-op for the app;
-- without it the Supabase anon key can read raw customer message bodies out
-- of "payload". No policy is created — nothing reads WebhookEvent through
-- PostgREST or Realtime.
ALTER TABLE "WebhookEvent" ENABLE ROW LEVEL SECURITY;
